# Generated by Django 5.1.1 on 2024-09-10 15:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0002_followsplaylist_followsuser_delete_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', regex='^[a-zA-Z0-9_.]*$')]),
        ),
    ]
