# Generated by Django 5.1.1 on 2024-09-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='cover_url',
            field=models.URLField(max_length=500),
        ),
    ]
