# Generated by Django 5.1.1 on 2024-09-25 13:34
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0004_alter_playlist_cover_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apple_music_access_token',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='apple_music_refresh_token',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='spotify_access_token',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='spotify_refresh_token',
            field=models.CharField(null=True),
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='user_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
