# Generated by Django 5.1.1 on 2024-10-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0005_user_apple_music_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
