# Generated by Django 5.1.1 on 2024-10-12 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0006_remove_user_email_remove_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=40, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', regex='^[a-zA-Z0-9_.]*$')]),
        ),
    ]
