# Generated by Django 5.1.1 on 2024-10-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0006_remove_user_email_remove_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
