# Generated by Django 5.1.1 on 2024-10-12 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0007_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='owner_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Database.user'),
            preserve_default=False,
        ),
    ]
