# Generated by Django 5.1.1 on 2024-10-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0008_playlist_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='origin_id',
            field=models.TextField(default=''),
        ),
    ]
