# Generated by Django 5.1.1 on 2024-10-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0009_playlist_origin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='cover_url',
            field=models.CharField(default='https://img.fotocommunity.com/papagei-frisst-loewenzahn-5b0326d5-65d2-4914-a1b6-1751830ed208.jpg?height=1080'),
        ),
    ]
