# Generated by Django 5.1.1 on 2024-10-14 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0009_playlist_origin_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followsplaylist',
            name='apple_music_id',
        ),
        migrations.RemoveField(
            model_name='followsplaylist',
            name='spotify_id',
        ),
    ]
